import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Providers from "@/app/providers";
import CartProvider from "@/context/CartItem";
import ConditionalHeader from "@/components/ConditionalHeader";
import SnowEffect from "@/components/SnowEffect";
import ChristmasMusic from "@/components/ChristmasMusic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food Dev",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ConditionalHeader />

          <SnowEffect />
          <ChristmasMusic />
          <CartProvider>{children}</CartProvider>
        </Providers>
        <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
